# Generated by Django 6.0.3 on 2026-03-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=150)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('KA_STATE', 'Karnataka State Board')], max_length=20)),
                ('grade', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prompt_input', models.TextField()),
                ('latex_output', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
