# Generated by Django 6.0.3 on 2026-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='courseplan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='courseplan',
            name='num_lessons',
            field=models.IntegerField(default=20),
        ),
    ]
