# Generated by Django 6.0.3 on 2026-03-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('KA_STATE', 'Karnataka State Board')], max_length=20)),
                ('language', models.CharField(default='English', max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['board', 'grade', 'subject'],
            },
        ),
    ]
